# Generated by Django 3.2.8 on 2021-10-31 21:48

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('z_neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, default='default bio', max_length=500)),
                ('location', models.CharField(blank=True, default='Umoja II', max_length=30, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634660213/image/upload/v1/images/profile/user.jpg', max_length=255, verbose_name='image')),
                ('contact_email', models.EmailField(blank=True, max_length=100)),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='z_neighborhood.neighborhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='z_neighborhood.userprofile'),
        ),
    ]
